name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t admin-api .

      - name: Install Dependencies
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/var/www \
            admin-api \
            composer install --no-interaction

      - name: Code Style Check
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/var/www \
            admin-api \
            ./vendor/bin/phpcs --parallel=1

      - name: Static Analysis
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/var/www \
            admin-api \
            ./vendor/bin/psalm --threads=4 --no-cache

      - name: Security Check
        uses: symfonycorp/security-checker-action@v5